# Question 1:
Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [1]:
import numpy as np

In [2]:
a = np.array([7, 6, 8, 2])
b = np.array([3, 6, 7, 9])
print('Original array:\n', a, '\n', b)
print('Comparison - greater\n', np.greater(a, b))
print('Comparison - greater_equal\n', np.greater_equal(a, b))
print('Comparison - less\n', np.less(a, b))
print('Comparison - less_equal\n', np.less_equal(a, b))

Original array:
 [7 6 8 2] 
 [3 6 7 9]
Comparison - greater
 [ True False  True False]
Comparison - greater_equal
 [ True  True  True False]
Comparison - less
 [False False False  True]
Comparison - less_equal
 [False  True False  True]


# Question 2:
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [3]:
# array of 10 zeros
a = np.zeros((10))
print('An array of 10 zeros:\n', a)

# array of 10 ones
b = np.ones((10))
print('An array of 10 ones:\n', b)

# array of 10 fives
c = np.ones((10))*5
print('An array of 10 fives:\n', c)

An array of 10 zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# Question 3:
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [4]:
a = np.arange(9).reshape(3,3)
print('Original array:\n', a)
print('Sum of all elements:\n', np.sum(a))
print('Sum of each column:\n', np.sum(a, axis=0))
print('Sum of each row:\n', np.sum(a, axis=1))

Original array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Sum of all elements:
 36
Sum of each column:
 [ 9 12 15]
Sum of each row:
 [ 3 12 21]


# Question 4:
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [5]:
print('Add:\n', np.add(5.0, 3.0))
print('Subtract:\n', np.subtract(5.0, 3.0))
print('Multiply:\n', np.multiply(5.0, 3.0))
print('Divide:\n', np.divide(5.0, 3.0))

Add:
 8.0
Subtract:
 2.0
Multiply:
 15.0
Divide:
 1.6666666666666667


# Question 5:
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [6]:
print('sine: array of angles given in degrees\n', np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print('cosine: array of angles given in degrees\n', np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print('tangent: array of angles given in degrees\n', np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

sine: array of angles given in degrees
 [0.         0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees
 [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent: array of angles given in degrees
 [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
