# Questions 1:

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

arr = np.arange(2, 51, 3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Questions 2:

Accept two lists of 5 elements each from the user.

Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
l1 = np.array(list(map(int, input().split())))
l2 = np.array(list(map(int, input().split())))

l = np.concatenate([l1, l2])
print(l)

print(sorted(l))

5 4 2 45 36
23 12 85 4 9
[ 5  4  2 45 36 23 12 85  4  9]
[2, 4, 4, 5, 9, 12, 23, 36, 45, 85]


# Questions 3:

Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
arr = np.arange(1, 31, 2).reshape(3, 5)
print(arr.shape)
print(arr.size)

(3, 5)
15


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

Hint: np.newaxis, np.expand_dims

In [8]:
# np.newaxis
arr = np.arange(6)
print(arr[:, np.newaxis]) # column vector
print(arr[:, np.newaxis].shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [9]:
# np.expand_dims
print(np.expand_dims(arr, axis=0))
print(np.expand_dims(arr, axis=0).shape)

[[0 1 2 3 4 5]]
(1, 6)


# Questions 5:

Consider two square numpy arrays. Stack them vertically and horizontally.

Hint: Use vstack(), hstack()

In [12]:
a = np.arange(1, 10).reshape(3,3)
b = np.arange(11, 20).reshape(3,3)

# vertically stacking
print(np.vstack((a, b)), '\n')

# horizontally stacking
print(np.hstack((a, b)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]] 

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


# Questions 6:

How to get unique items and counts of unique items?

In [24]:
arr = np.array([1, 9, 3, 3, 4 ,4, 2, 1, 3, 5, 7, 5])
print(arr)
unique_elements, counts_elements = np.unique(arr, return_counts=True)

# unique values
print(unique_elements)

# count elements
print(counts_elements)

[1 9 3 3 4 4 2 1 3 5 7 5]
[1 2 3 4 5 7 9]
[2 1 3 2 2 1 1]
